import React, { useState, useEffect } from "react";
import Head from "next/head";

import styles from "../styles/Admin.module.scss";
import Loanding from "../components/loading/Loanding";
import Header from "../components/header/header";

import { HiPencil } from "react-icons/hi";

export default function AdminPage() {
  const [isLoading, setIsLoading] = useState(true);
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    async function loadData() {
      setIsLoading(true);
      const api = await fetch("http://localhost:3000/movies");
      const result = await api.json();
      setMovies(result);
      setIsLoading(false);
    }

    loadData();
  }, []);

  function getId(id) {
    location.href = `/editReview/${id}`;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h3>hello</h3>
      {isLoading ? (
        <div>
          <Loanding />
        </div>
      ) : (
        <main className={styles.main}>
          <ol className={styles.box}>
            {movies.map((movie) => (
              <li className={styles.movieContainer} key={movie.id}>
                <span>{movie.title}</span>
                <div className={styles.buttons}>
                  <a
                    onClick={() => getId(movie.id)}
                    className={styles.editButton}
                  >
                    <HiPencil />
                  </a>
                  {/* <button className={styles.trashButton}>
                    <HiOutlineTrash />
                  </button> */}
                </div>
              </li>
            ))}
          </ol>
        </main>
      )}
    </div>
  );
}
