/* eslint-disable @next/next/no-img-element */
import React, { useState, useEffect } from "react";

import Head from "next/head";
import Loanding from "../components/loading/Loanding";

import styles from "../styles/Favorites.module.scss";
import Card from "../components/card/card";
import Header from "../components/header/header";
import { HiHeart } from "react-icons/hi";

export default function Favorites() {
  const [isLoading, setIsLoading] = useState(true);

  const [favorites, setFavorites] = useState([]);

  useEffect(() => {
    setIsLoading(true);
    const data = localStorage.getItem("favorites");
    setIsLoading(false);
    if (data) {
      setFavorites(JSON.parse(data));
    }
  }, []);

  console.log(favorites);
  return (
    <div className={styles.container}>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie-icon.svg" />
      </Head>

      <Header />
      {isLoading ? (
        <main className={styles.main}>
          <Loanding />
        </main>
      ) : (
        <main className={styles.main}>
          <section className={styles.movieSection}>
            <div className={styles.favoritesTitle}>
              <h1>
                <HiHeart />
                Favorites - <p>{favorites.length}</p>
              </h1>
              <div className={styles.line} />
            </div>
            <div className={styles.cardsContainer}>
              {favorites.map((movie) => (
                <div className={styles.card} key={movie.id}>
                  <Card
                    title={movie.title}
                    image={movie.movieImg}
                    stars={movie.stars}
                    id={movie.id}
                  />
                </div>
              ))}
            </div>
          </section>
        </main>
      )}
    </div>
  );
}
