/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import Typewriter from "typewriter-effect";

import styles from "../styles/Home.module.scss";
import { useState, useEffect } from "react";

import Header from "../components/header/header";

import { HiArrowNarrowRight } from "react-icons/hi";

export default function Home() {
  const [header, setHeader] = useState("header");

  useEffect(() => {
    function componentDidMount() {
      window.addEventListener("scroll", listenScrollEvent);
    }

    function listenScrollEvent() {
      if (window.scrollY > 800) {
        setHeader("header");
      } else if (window.scrollY < 800) {
        setHeader("header2");
      }
    }

    componentDidMount();
  }, [header, setHeader]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Movies Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie-logo.svg" />
      </Head>

      <main className={styles.main}>
        <Header />

        <section className={styles.sectionContainer}>
          <div className={styles.textContainer}>
            <div className={styles.text}>
              <h1>
                <Typewriter
                  className={styles.typewriter}
                  onInit={(typewriter) => {
                    typewriter
                      .typeString("Welcome to Movie Reviews")
                      .pauseFor(1500)
                      .deleteAll()
                      .start();
                  }}
                  options={{
                    autoStart: true,
                    loop: true,
                  }}
                />
              </h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Tellus in hac habitasse platea dictumst vestibulum rhoncus. Amet
                facilisis magna etiam tempor orci eu lobortis elementum nibh.
              </p>

              <div className={styles.linkDiv}>
                <Link href="./reviews">
                  <a>
                    See all reviews
                    <HiArrowNarrowRight className={styles.rightIcon} />
                  </a>
                </Link>
              </div>
            </div>
          </div>

          <div className={styles.imageContainer}>
            <img src="/Film-rolls.svg" alt="Cinema Illustration" />
          </div>
        </section>
      </main>
    </div>
  );
}
