import React, { useState, useEffect } from "react";
import Header from "../components/header/header";
import Head from "next/head";
import styles from "../styles/NewReview.module.scss";

export default function NewReview() {
  const [movie, setMovie] = useState({});

  const [movieTitle, setMovieTitle] = useState(undefined);
  const [description, setDescription] = useState(undefined);
  const [director, setDirector] = useState(undefined);
  const [movieImg, setMovieImg] = useState(undefined);
  const [review, setReview] = useState(undefined);
  const [stars, setStars] = useState(undefined);

  const [newReview, setnewReview] = useState({});

  function addReview() {
    const newReview = {
      title: movieTitle,
      description: description,
      stars: stars,
      movieImg: movieImg,
      review: review,
      director: director,
    };

    setnewReview(newReview);
  }

  useEffect(() => {
    async function addMovie() {
      const requestOptions = {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newReview),
      };
      const api = await fetch("http://localhost:3000/movies", requestOptions);
      const data = await api.json();
      setMovie(data);
    }

    addMovie();
  }, [newReview]);

  console.log(movie);

  return (
    <div>
      <Head>
        <title>New Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.inputContainer}>
          <h1>Add a new review</h1>
          <input
            className={styles.title}
            placeholder="Title"
            onChange={(e) => setMovieTitle(e.target.value)}
            type="text"
          />
          <input
            className={styles.stars}
            placeholder="Stars"
            onChange={(e) => setStars(e.target.value)}
            type="number"
          />

          <input
            className={styles.director}
            placeholder="Director"
            onChange={(e) => setDirector(e.target.value)}
            type="text"
          />
          <input
            className={styles.poster}
            placeholder="Poster"
            onChange={(e) => setMovieImg(e.target.value)}
            type="text"
          />

          <input
            className={styles.description}
            placeholder="Description"
            onChange={(e) => setDescription(e.target.value)}
            type="text"
          />
          <input
            className={styles.review}
            placeholder="Review"
            onChange={(e) => setReview(e.target.value)}
            type="text"
          />

          <button
            type="submit"
            onClick={addReview}
            disabled={movieTitle === undefined}
          >
            Add review
          </button>
        </div>
      </main>
    </div>
  );
}
