import React, { useState, useEffect } from "react";
import Header from "../components/header/header";
import Head from "next/head";
import styles from "../styles/NewReview.module.scss";
import toast, { Toaster } from "react-hot-toast";

export default function NewReview() {
  const [movie, setMovie] = useState({});
  const [newReview, setnewReview] = useState({});
  const [sendNewReview, setSendNewReview] = useState(false);

  const [movieTitle, setMovieTitle] = useState(undefined);
  const [description, setDescription] = useState(undefined);
  const [director, setDirector] = useState(undefined);
  const [movieImg, setMovieImg] = useState(undefined);
  const [review, setReview] = useState(undefined);
  const [stars, setStars] = useState(undefined);

  const allInfos =
    movieTitle && movieImg && description && director && review && stars;

  console.log(movie);

  function addReview(e) {
    e.preventDefault();

    if (allInfos != undefined && allInfos !== "") {
      toast.success("Review added", { icon: "💜" });

      const newReviewData = {
        title: movieTitle,
        description: description,
        stars: stars,
        movieImg: movieImg,
        review: review,
        director: director,
      };

      setnewReview(newReviewData);
      setSendNewReview(true);
    } else {
      toast.error("Please fill in all fields");
    }
  }

  useEffect(() => {
    async function addingReview() {
      if (sendNewReview === true) {
        const requestOptions = {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(newReview),
        };
        fetch("http://localhost:3000/movies", requestOptions)
          .then((response) => response.json())
          .then((data) => setMovie(data.id));
      } else {
        null;
      }
    }
    addingReview();
  }, [sendNewReview, newReview]);

  return (
    <div>
      <Head>
        <title>New Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movie-icon.svg" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.inputContainer}>
          <h1>Add a new review</h1>
          <form>
            <div className={styles.inputDiv}>
              <label htmlFor="Title">Title</label>
              <input
                className={styles.title}
                placeholder="Title"
                onChange={(e) => setMovieTitle(e.target.value)}
                type="text"
                required="required"
                name="Title"
                id="Title"
              />
            </div>

            <div className={styles.inputDiv}>
              <label htmlFor="Stars">Stars</label>
              <input
                className={styles.stars}
                placeholder="Stars"
                onChange={(e) => setStars(e.target.value)}
                type="number"
                required="required"
                name="Stars"
                id="Stars"
              />
            </div>

            <div className={styles.inputDiv}>
              <label htmlFor="Director">Director</label>
              <input
                className={styles.director}
                placeholder="Director"
                onChange={(e) => setDirector(e.target.value)}
                type="text"
                required="required"
                name="Director"
                id="Director"
              />
            </div>

            <div className={styles.inputDiv}>
              <label htmlFor="MovieImg">Poster Url</label>
              <input
                className={styles.poster}
                placeholder="Poster"
                onChange={(e) => setMovieImg(e.target.value)}
                type="text"
                required="required"
                name="Movie Image"
                id="MovieImg"
              />
            </div>

            <div className={styles.inputDiv}>
              <label htmlFor="Description">Description</label>
              <input
                className={styles.description}
                placeholder="Description"
                onChange={(e) => setDescription(e.target.value)}
                type="text"
                required="required"
                name="Description"
                id="Description"
              />
            </div>

            <div className={styles.inputDiv}>
              <label htmlFor="Review">Review</label>
              <input
                className={styles.review}
                placeholder="Review"
                onChange={(e) => setReview(e.target.value)}
                type="text"
                required="required"
                name="Review"
                id="Review"
              />
            </div>

            <button
              type="submit"
              onClick={addReview}
              disabled={movieTitle === ""}
            >
              Add review
            </button>
          </form>
          <Toaster />
        </div>
      </main>
    </div>
  );
}
